### ISSUE TITLE
Документация по работе с АПИ 

### ISSUE THREAD

**Issue by Karim90403** [stankin/mj#29]
Можете пожалуйста написать документацию по работе с АПИ, я разрабатываю ве версию модульного журнала с полным функционалом

Хочу добавить плотную работу с вашим сервисом

1. Аутентификация(Я бы хотел без редиректа, внутри сайта)
2. Работа с модулями
3. Работа с расписанием

https://github.com/Karim90403/stankin_modules - мой сервис

**Comment by xiexed** [comment]
Да не то чтобы у неё есть какое-то специальное API...
Есть [API авторизации](https://github.com/stankin/mj/blob/master/oauthProvider.md#использование-модульного-журнала-как-oauth2-провайдера-beta), в принципе туда можно добавить всё что угодно. Если авторизация для вас работает, я могу добавить туда например выгрузку оценок текущего пользователя.

Если нужна какая-то другая авторизация - давайте придумаем как её сделать. Если пользователи будут вводить пароль у вас в форме - то это вообще не проблема. `Basic`-аутентификация и сейчас работает в любом случае (если при каждом запросе передавать пароль)

Есть старый [Api](https://github.com/stankin/mj/blob/master/src/main/java/ru/stankin/mj/http/HttpApi2.java) для выгрузки модулей по паролю.
